In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4,5,6,7,8,9,10]


In [15]:
lista[0] = 9
print(lista)

[9, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [6]:
array = np.array(lista)

In [8]:
print(type(lista))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [14]:
matriz_zero = np.zeros((10,4))
print(matriz_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
# Notas dos Alunos
Turma = input(str("Turma: "))
i = int(input("Quantidade de alunos: "))
notas = []
for i in range(0,i):
    n = float(input("digite a nota"))
    notas.append(n)
                    
notas_array = np.array(notas)
print("Turma: ", Turma)
print("Quantidade de Alunos: ",  i)
print("Nota Máxima: ", notas_array.max())
print("Nota Mínima: ", notas_array.min())
print("Desvio padrão: ", notas_array.std())
print("Média da Turma: ", notas_array.mean())



Turma:  9 - B
Quantidade de alunos:  5
digite a nota 10
digite a nota 9.5
digite a nota 6.3
digite a nota 2.4
digite a nota 1


Turma:  9 - B
Quantidade de Alunos:  4
Nota Máxima:  10.0
Nota Mínima:  1.0
Desvio padrão:  3.6379114887528528
Média da Turma:  5.84
